version: '3.2'

services:
  db:
    image: "mariadb:10.5"
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwdabc
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci', '--transaction-isolation=READ-COMMITTED']
    volumes:
      - type: bind
        source: ./misc/db
        target: /docker-entrypoint-initdb.d
        volume:
          readonly: true
